// 🌟 FORM SCHEMAS DATABASE
const formSchemas = {
  registration: [
    {
      id: 1,
      label: "Full Name",
      type: "text",
      placeholder: "John Doe",
      required: true,
    },
    {
      id: 2,
      label: "Email Address",
      type: "email",
      placeholder: "john@example.com",
      required: true,
    },
    {
      id: 3,
      label: "Password",
      type: "password",
      placeholder: "********",
      required: true,
    },
  ],
  contact: [
    {
      id: 1,
      label: "Name",
      type: "text",
      placeholder: "Your Name",
      required: true,
    },
    {
      id: 2,
      label: "Email",
      type: "email",
      placeholder: "Your Email",
      required: true,
    },
    {
      id: 3,
      label: "Message",
      type: "textarea",
      placeholder: "How can we help?",
      required: true,
    },
  ],
  survey: [
    {
      id: 1,
      label: "How did you hear about us?",
      type: "select",
      options: ["Facebook", "Google", "Friend", "Other"],
      required: false,
    },
    {
      id: 2,
      label: "Would you recommend us?",
      type: "radio",
      options: ["Yes", "No", "Maybe"],
      required: true,
    },
    {
      id: 3,
      label: "Subscribe to newsletter?",
      type: "checkbox",
      placeholder: "Yes, subscribe me",
      required: false,
    },
    {
      id: 4,
      label: "Additional Feedback",
      type: "textarea",
      placeholder: "Tell us more...",
      required: false,
    },
  ],
  general: [
    {
      id: 1,
      label: "Title",
      type: "text",
      placeholder: "Enter title here",
      required: true,
    },
    {
      id: 2,
      label: "Description",
      type: "textarea",
      placeholder: "Enter details...",
      required: false,
    },
  ],
  eventRSVP: [
    {
      id: 1,
      label: "Full Name",
      type: "text",
      placeholder: "John Doe",
      required: true,
    },
    {
      id: 2,
      label: "Email Address",
      type: "email",
      placeholder: "john@example.com",
      required: true,
    },
    {
      id: 3,
      label: "Phone Number",
      type: "tel",
      placeholder: "012 345 6789",
      required: false,
    },
    {
      id: 4,
      label: "Will You Attend?",
      type: "select",
      options: ["Yes", "No", "Maybe"],
      required: true,
    },
    {
      id: 5,
      label: "Dietary Restrictions",
      type: "textarea",
      placeholder: "Vegetarian, Gluten-Free, etc.",
      required: false,
    },
    {
      id: 6,
      label: "Additional Comments",
      type: "textarea",
      placeholder: "Any other details?",
      required: false,
    },
  ],
  productFeedback: [
    {
      id: 1,
      label: "Product Name",
      type: "text",
      placeholder: "Product ABC",
      required: true,
    },
    {
      id: 2,
      label: "Rating",
      type: "select",
      options: [
        "1 - Poor",
        "2 - Fair",
        "3 - Good",
        "4 - Very Good",
        "5 - Excellent",
      ],
      required: true,
    },
    {
      id: 3,
      label: "Would You Recommend This Product?",
      type: "radio",
      options: ["Yes", "No"],
      required: true,
    },
    {
      id: 4,
      label: "What Did You Like?",
      type: "textarea",
      placeholder: "Explain what you liked...",
      required: false,
    },
    {
      id: 5,
      label: "What Can Be Improved?",
      type: "textarea",
      placeholder: "Explain what can be improved...",
      required: false,
    },
  ],
  volunteerSignup: [
    {
      id: 1,
      label: "Full Name",
      type: "text",
      placeholder: "John Doe",
      required: true,
    },
    {
      id: 2,
      label: "Email Address",
      type: "email",
      placeholder: "john@example.com",
      required: true,
    },
    {
      id: 3,
      label: "Phone Number",
      type: "tel",
      placeholder: "012 345 6789",
      required: true,
    },
    {
      id: 4,
      label: "Availability",
      type: "select",
      options: ["Morning", "Afternoon", "Evening"],
      required: true,
    },
    {
      id: 5,
      label: "Preferred Volunteer Role",
      type: "text",
      placeholder: "e.g., Event Coordinator",
      required: false,
    },
    {
      id: 6,
      label: "Why Do You Want to Volunteer?",
      type: "textarea",
      placeholder: "Share your motivation...",
      required: true,
    },
    {
      id: 7,
      label: "Previous Experience",
      type: "textarea",
      placeholder: "Any relevant experience?",
      required: false,
    },
  ],
  complaint: [
    {
      id: 1,
      label: "Full Name",
      type: "text",
      placeholder: "John Doe",
      required: true,
    },
    {
      id: 2,
      label: "Phone Number",
      type: "tel",
      placeholder: "012 345 6789",
      required: true,
    },
    { id: 3, label: "Incident Date", type: "date", required: true },
    {
      id: 4,
      label: "Department / Category",
      type: "select",
      options: [
        "Customer Service",
        "Product Quality",
        "Delivery Issue",
        "Other",
      ],
      required: true,
    },
    {
      id: 5,
      label: "Complaint Details",
      type: "textarea",
      placeholder: "Please describe the issue in detail...",
      required: true,
    },
    { id: 6, label: "Upload Proof (Optional)", type: "file", required: false },
  ],
  jobApplication: [
    {
      id: 1,
      label: "Full Name",
      type: "text",
      placeholder: "Your Full Name",
      required: true,
    },
    {
      id: 2,
      label: "Email",
      type: "email",
      placeholder: "you@email.com",
      required: true,
    },
    {
      id: 3,
      label: "Phone Number",
      type: "tel",
      placeholder: "012 345 6789",
      required: true,
    },
    {
      id: 4,
      label: "Position Applying For",
      type: "text",
      placeholder: "e.g., Software Engineer",
      required: true,
    },
    { id: 5, label: "Upload Resume/CV", type: "file", required: true },
    {
      id: 6,
      label: "Cover Letter",
      type: "textarea",
      placeholder: "Tell us why you are a good fit...",
      required: false,
    },
  ],
  appointmentBooking: [
    {
      id: 1,
      label: "Patient/Client Name",
      type: "text",
      placeholder: "Full Name",
      required: true,
    },
    {
      id: 2,
      label: "Phone Number",
      type: "tel",
      placeholder: "012 345 6789",
      required: true,
    },
    { id: 3, label: "Preferred Date", type: "date", required: true },
    { id: 4, label: "Preferred Time", type: "time", required: true },
    {
      id: 5,
      label: "Reason for Appointment",
      type: "textarea",
      placeholder: "Briefly describe the reason...",
      required: true,
    },
  ],

  // 🌟 NEW: IT Support Ticket
  itSupport: [
    {
      id: 1,
      label: "Employee Name",
      type: "text",
      placeholder: "Jane Doe",
      required: true,
    },
    {
      id: 2,
      label: "Department",
      type: "select",
      options: ["HR", "Finance", "Engineering", "Marketing", "Other"],
      required: true,
    },
    {
      id: 3,
      label: "Device Type",
      type: "radio",
      options: ["Laptop", "Desktop", "Mobile", "Printer"],
      required: true,
    },
    {
      id: 4,
      label: "Issue Urgency",
      type: "select",
      options: ["Low", "Medium", "High", "Critical"],
      required: true,
    },
    {
      id: 5,
      label: "Describe the Issue",
      type: "textarea",
      placeholder: "What seems to be the problem?",
      required: true,
    },
    { id: 6, label: "Screenshot of Error", type: "file", required: false },
  ],

  // 🌟 NEW: Multi-Step / Wizard Registration (Shows how page-break works)
  multiStepRegistration: [
    {
      id: 1,
      label: "First Name",
      type: "text",
      placeholder: "John",
      required: true,
    },
    {
      id: 2,
      label: "Last Name",
      type: "text",
      placeholder: "Doe",
      required: true,
    },
    {
      id: 3,
      label: "Email",
      type: "email",
      placeholder: "john@example.com",
      required: true,
    },
    { id: 4, label: "Address Details", type: "page-break", required: false }, // Creates Step 2
    {
      id: 5,
      label: "Street Address",
      type: "text",
      placeholder: "123 Main St",
      required: true,
    },
    {
      id: 6,
      label: "City",
      type: "text",
      placeholder: "New York",
      required: true,
    },
    { id: 7, label: "Preferences", type: "page-break", required: false }, // Creates Step 3
    {
      id: 8,
      label: "Choose Plan",
      type: "radio",
      options: ["Basic", "Pro", "Enterprise"],
      required: true,
    },
    {
      id: 9,
      label: "Accept Terms",
      type: "checkbox",
      placeholder: "I agree to the terms",
      required: true,
    },
  ],

  // === KHMER FORM TYPES ===
  អាពាហ៍ពិពាហ៍: [
    {
      id: 1,
      label: "ឈ្មោះភ្ញៀវ",
      type: "text",
      placeholder: "បញ្ចូលឈ្មោះរបស់អ្នក...",
      required: true,
    },
    {
      id: 2,
      label: "លេខទូរស័ព្ទ",
      type: "tel",
      placeholder: "០១២ ៣៤៥ ៦៧៨",
      required: false,
    },
    {
      id: 3,
      label: "តើអ្នកនឹងចូលរួមទេ?",
      type: "select",
      options: ["ចូលរួម", "មិនបានចូលរួម"],
      required: true,
    },
    {
      id: 4,
      label: "ចំណងដៃ / សារជូនពរ",
      type: "textarea",
      placeholder: "សរសេរសាររបស់អ្នកនៅទីនេះ...",
      required: false,
    },
  ],
  ចុះឈ្មោះសកម្មភាព: [
    {
      id: 1,
      label: "ឈ្មោះពេញ",
      type: "text",
      placeholder: "បញ្ចូលឈ្មោះពេញ...",
      required: true,
    },
    {
      id: 2,
      label: "ភេទ",
      type: "select",
      options: ["ប្រុស", "ស្រី", "ផ្សេងៗ"],
      required: false,
    },
    {
      id: 3,
      label: "លេខទូរស័ព្ទ",
      type: "tel",
      placeholder: "០១២ ៣៤៥ ៦៧៨",
      required: true,
    },
    {
      id: 4,
      label: "អ៊ីមែល",
      type: "email",
      placeholder: "example@email.com",
      required: false,
    },
  ],
  ចុះឈ្មោះចូលលេងកីឡា: [
    {
      id: 1,
      label: "ឈ្មោះពេញ",
      type: "text",
      placeholder: "បញ្ចូលឈ្មោះរបស់អ្នក",
      required: true,
    },
    {
      id: 2,
      label: "ភេទ",
      type: "radio",
      options: ["មនុស្សប្រុស", "មនុស្សស្រី"],
      required: true,
    },
    {
      id: 3,
      label: "ជ្រើសរើសក្រុម",
      type: "select",
      options: ["ក្រុម A", "ក្រុម B", "ក្រុម C"],
      required: true,
    },
    {
      id: 4,
      label: "លេខទូរស័ព្ទ",
      type: "tel",
      placeholder: "០១២ ៣៤៥ ៦៧៨",
      required: true,
    },
  ],
  ដាក់ពាក្យបណ្តឹង: [
    {
      id: 1,
      label: "ឈ្មោះអ្នកប្តឹង",
      type: "text",
      placeholder: "បញ្ចូលឈ្មោះរបស់អ្នក",
      required: true,
    },
    {
      id: 2,
      label: "លេខទូរស័ព្ទ",
      type: "tel",
      placeholder: "០១២ ៣៤៥ ៦៧៨",
      required: true,
    },
    { id: 3, label: "កាលបរិច្ឆេទកើតហេតុ", type: "date", required: true },
    {
      id: 4,
      label: "ប្រភេទបណ្តឹង",
      type: "select",
      options: ["សេវាកម្មមិនល្អ", "ទំនិញខូចគុណភាព", "បញ្ហាដឹកជញ្ជូន", "ផ្សេងៗ"],
      required: true,
    },
    {
      id: 5,
      label: "ពណ៌នាពីបញ្ហា",
      type: "textarea",
      placeholder: "សូមសរសេរលម្អិតពីបញ្ហាដែលបានកើតឡើង...",
      required: true,
    },
    { id: 6, label: "ឯកសារភ្ជាប់ (បើមាន)", type: "file", required: false },
  ],
  កក់ការណាត់ជួប: [
    {
      id: 1,
      label: "ឈ្មោះអតិថិជន",
      type: "text",
      placeholder: "បញ្ចូលឈ្មោះរបស់អ្នក",
      required: true,
    },
    {
      id: 2,
      label: "លេខទូរស័ព្ទ",
      type: "tel",
      placeholder: "០១២ ៣៤៥ ៦៧៨",
      required: true,
    },
    { id: 3, label: "កាលបរិច្ឆេទចង់ជួប", type: "date", required: true },
    { id: 4, label: "ម៉ោង", type: "time", required: true },
    {
      id: 5,
      label: "គោលបំណង",
      type: "textarea",
      placeholder: "មូលហេតុនៃការណាត់ជួប...",
      required: true,
    },
  ],

  // 🌟 NEW KHMER: Order Form
  កុម្ម៉ង់ទំនិញ: [
    { id: 1, label: "ព័ត៌មានអតិថិជន", type: "page-break", required: false },
    {
      id: 2,
      label: "ឈ្មោះអ្នកទិញ",
      type: "text",
      placeholder: "ឈ្មោះរបស់អ្នក",
      required: true,
    },
    {
      id: 3,
      label: "លេខទូរស័ព្ទ",
      type: "tel",
      placeholder: "០១២ ៣៤៥ ៦៧៨",
      required: true,
    },
    { id: 4, label: "ព័ត៌មានដឹកជញ្ជូន", type: "page-break", required: false },
    {
      id: 5,
      label: "ទីតាំងដឹកជញ្ជូន",
      type: "textarea",
      placeholder: "ផ្ទះលេខ, ផ្លូវ, សង្កាត់...",
      required: true,
    },
    {
      id: 6,
      label: "ប្រភេទសេវាដឹក",
      type: "select",
      options: ["ដឹកធម្មតា (1-2 ថ្ងៃ)", "ដឹកលឿន (ថ្ងៃនេះ)"],
      required: true,
    },
  ],
};

module.exports = formSchemas;
